#! /bin/sh

sxhkd &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            12

bspc config focused_border_color  "#FFFFFF"
bspc config presel_feedback_color "#FFFFFF"

bspc config split_ratio           0.52
bspc config single_monocle        false
bspc config top_padding           35
bspc config focus_follows_pointer true


bspc rule -a Firefox state=tiled
bspc rule -a Nightly state=tiled

bspc rule -a plasmashell state=floating

bspc rule -a libreoffice-writer state=tiled
bspc rule -a libreoffice-impress state=tiled
bspc rule -a libreoffice-calc state=tiled

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
